const PRODUCTS = [
    {
        id: 1,
        name: "Metro Mobile",
        price: "39.99",
        like: "true",
        img: require("../assets/1.png"),
        about: "Next generation phone for the human being mobile",
    },

    {
        id: 1,
        name: "Metro Mobile",
        price: "39.99",
        like: "true",
        img: require("../assets/1.png"),
        about: "Next generation phone for the human being mobile",
    },
    {
        id: 1,
        name: "Metro Mobile",
        price: "39.99",
        like: "true",
        img: require("../assets/1.png"),
        about: "Next generation phone for the human being mobile",
    },
    {
        id: 1,
        name: "Metro Mobile",
        price: "39.99",
        like: "true",
        img: require("../assets/1.png"),
        about: "Next generation phone for the human being mobile",
    },
    {
        id: 1,
        name: "Metro Mobile",
        price: "39.99",
        like: "true",
        img: require("../assets/1.png"),
        about: "Next generation phone for the human being mobile",
    },
    {
        id: 1,
        name: "Metro Mobile",
        price: "39.99",
        like: "true",
        img: require("../assets/1.png"),
        about: "Next generation phone for the human being mobile",
    },
    {
        id: 1,
        name: "Metro Mobile",
        price: "39.99",
        like: "true",
        img: require("../assets/1.png"),
        about: "Next generation phone for the human being mobile",
    },
    {
        id: 1,
        name: "Metro Mobile",
        price: "39.99",
        like: "true",
        img: require("../assets/1.png"),
        about: "Next generation phone for the human being mobile",
    },
]